### ISSUE TITLE
Error when using verbose mode

### ISSUE THREAD

**Issue by ruyadorno** [zeachco/stubborn-server#4]
If in the configs I set the option `verbose:true`, I get the following error:

```
TypeError: Cannot read property 'replace' of undefined
    at args.map (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/stubborn-server/server/logger.js:14:18)
    at Object.module.exports.verbose.debug (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/stubborn-server/server/logger.js:41:7)
    at /Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/stubborn-server/server/mocks.js:50:11
    at Layer.handle [as handle_request] (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:312:13)
    at /Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/body-parser/lib/types/json.js:100:40)
    at Layer.handle [as handle_request] (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:312:13)
    at /Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/Users/ruy.adorno/Documents/workspace/ad-spa-tests/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by zeachco** [comment]
@ruyadorno do you still have that issue? can't reproduce
